server:
  port: 8080

spring:
  application:
    name: badminton-booking

  datasource:
    url: jdbc:mysql://localhost:3306/badminton_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: dangtoan2006
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB

jwt:
  secret: 45t6ysudfsdjifgjwe8s-weihf833p4k
  access-token-expiration: 900000       # 15 phút (ms)
  refresh-token-expiration: 604800000   # 7 ngày (ms)

Cloudinary:
  cloud-name: cloudinaryDangToan
  api-key: 156859274255491
  api-secret: uB2aPFq95xlIueJEyMX1kSRyq4A

logging:
  level:
    com.example.badmintonbooking: DEBUG
    org.springframework.security: DEBUG
  file:
    name: logs/application.log